ARG NODE_IMAGE=node:20.14.0-bookworm-slim

FROM $NODE_IMAGE AS base

# All deps stage
FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install --force

# Production only deps stage
FROM base AS production-deps
WORKDIR /app
COPY package*.json ./
RUN npm install --force

# Build stage
FROM base AS build
WORKDIR /app
COPY --from=deps /app/node_modules /app/node_modules
COPY . .
RUN node ace build

# Production stage
FROM base
ENV NODE_ENV=production
WORKDIR /app
COPY --from=production-deps /app/node_modules /app/node_modules
COPY --from=build /app/build /app


RUN npm i -g @redocly/cli@latest

RUN apt-get update && apt-get install -y default-mysql-client && rm -rf /var/lib/apt/lists/*

EXPOSE $PORT
